apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet5flash-deployment
spec:
  selector:
    matchLabels:
      app: dotnet5flash
  template:
    metadata:
      labels:
        app: dotnet5flash
    spec:
      containers:
        - name: dotnet5flash
          image: nhatquangta2911/dotnet5flash:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoDbSettings__Host
              value: mongodb-service
            - name: MongoDbSettings__Password
              valueFrom:
                secretKeyRef:
                  name: dotnet5flash-secret
                  key: mongodb-password
          livenessProbe:
            httpGet:
              path: "healthcheck/live"
              port: 80
          readinessProbe:
            httpGet:
              path: "healthcheck/ready"
              port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dotnet5flash-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet5flash
  ports:
    - port: 80
      targetPort: 80
